Repository guddnboy/MONEY-TTO, pull requests merged in 2025-04, with the labels that each got.

#39 design: 캘린더 버튼, 요일 텍스트 스타일 수정
  src/components/Calendar.vue
Labels: style

#40 Fix: 메인페이지, 헤더 수입/지출 값 오류 (#33)
  src/components/Header.vue
  src/components/MonthAnalysis.vue
  src/pages/Home.vue
Labels: bug

#41 fix: 일 단위로 수입/ 지출 총액 표시로 수정
  src/components/Calendar.vue
Labels: bug

#47 design: 회원가입 디자인, 차트 디자인 수정
  db.json
  src/components/Header.vue
  src/pages/EditProfile.vue
  src/pages/Home.vue
  src/pages/Login.vue
  src/pages/Register.vue
  src/pages/transactions/AddTrade.vue
  src/pages/transactions/EditTrade.vue
  src/pages/transactions/TradeDetail.vue
  src/utils/auth-util.js
  src/utils/month-analysis.js
  vite.config.js
Labels: bug, style

#49 design: 전역 폰트 설정
  src/assets/main.css
  src/assets/styles/main.css
  src/main.js
Labels: style

#67 fi: 나이 값 음수 처리
  src/pages/EditProfile.vue
  src/pages/Register.vue
Labels: bug

#68 fix: 금액 제한 설정
  src/pages/AddTrade.vue
  src/pages/EditTrade.vue
Labels: bug

#80 fix: 내역 추가 페이지 아래 버튼 겹침 문제 해결
  src/pages/AddTrade.vue
Labels: bug
